bayes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core import views
from rest_framework import routers
from api.views import BaysianNetViewSet, LogSessionViewSet, GameSessionViewSet, ConditionalProbabilityViewSet

router = routers.DefaultRouter()
router.register(r'nets', BaysianNetViewSet)
router.register(r'logs', LogSessionViewSet)
router.register(r'session', GameSessionViewSet)
router.register(r'ctp', ConditionalProbabilityViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
    url(r'^baysianet/new/$', views.baysianet_new, name='baysianet_new'),
    url(r'^baysianet/(?P<pk>[0-9]+)/$', views.baysianet_detail, name='net_detail'),
    url(r'^competence/new/(?P<baysianet_pk>[0-9]+)$', views.competence_new, name='competency_new'),
    url(r'^baysianet/hierarchy/new/(?P<baysianet_pk>[0-9]+)$', views.hierarchy_new, name='hierarchy_new'),
    url(r'^competence/variable/new/(?P<competency_pk>[0-9]+)/(?P<baysianet_pk>[0-9]+)$', views.variable_new, name='variable_new'),
    url(r'^baysianet/cpt/new/(?P<competency_pk>[0-9]+)/(?P<baysianet_pk>[0-9]+)$', views.ctp_new, name='ctp_new'),
    url(r'^baysianet/cpt/detail/(?P<competency_pk>[0-9]+)/(?P<baysianet_pk>[0-9]+)$', views.ctp_detail, name='ctp_detail'),
    url(r'^competence/(?P<pk>[0-9]+)/$', views.competence_detail),
    url(r'^api/', include(router.urls)),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^register/$', views.register),
    url(r'^games/$', views.games, name='games'),
    url(r'^games/play/(?P<game_pk>[0-9]+)$', views.play, name='play'),
    url(r'^relatorios/(?P<game_pk>[0-9]+)$', views.relatorios, name='relatorios'),
    url(r'^relatorios/(?P<user_pk>[0-9]+)/(?P<game_pk>[0-9]+)$', views.relatorio_individual, name='relatorio_individual'),
    url(r'^relatorios/simulator/(?P<session_pk>[0-9]+)$', views.simulator, name='simulator'),

]

core/models.py
from django.db import models

# Create your models here.

class BaysianNet(models.Model):
    title = models.CharField(max_length=200, verbose_name='Título')
    text = models.TextField(verbose_name='Postagem', help_text='Informações')
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

# ######################################
# Proficiency Model
# defines one or more variables related to the knowledge,
# skills, and abilities we wish to measure.
class Competence(models.Model):
    title = models.CharField(max_length=200, verbose_name='Título')
    text = models.TextField(verbose_name='Postagem', help_text='Informações')
    baysianet = models.ForeignKey('BaysianNet', related_name='competency')
    #competencs = models.ManyToManyField('Competence', blank=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Variable(models.Model):
    title = models.CharField(max_length=200, verbose_name='Título')
    value = models.CharField(max_length=200, verbose_name='Valor', help_text='Valor da variável', blank=True)
    competence = models.ForeignKey(Competence, related_name='variable')
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

# Struture for expressing multidimensional relationships
class Hierarchy(models.Model):
    baysianet = models.ForeignKey('BaysianNet')
    competency_father = models.ForeignKey(Competence, related_name='father')
    competency_child = models.ForeignKey(Competence, related_name='child')

    def __str__(self):
        return self.competency_father.title


class ConditionalProbabilityTable(models.Model):
    baysianet = models.ForeignKey('BaysianNet')
    competency_father = models.ForeignKey(Competence, related_name='cpt_father')
    variable_father = models.ForeignKey(Variable, related_name='father')
    variable_child = models.ForeignKey(Variable, related_name='child')
    value = models.CharField(max_length=200, verbose_name='Valor', help_text='Valor da variável', blank=True)
    line = models.IntegerField(verbose_name='Linha', null=True, blank=True)

    def __str__(self):
        return self.variable_father.competence.title

# ######################################
# Models for resolve sessions user
# ######################################
class Game(models.Model):
    title = models.CharField(max_length=200, verbose_name='Título')
    text = models.TextField(verbose_name='Postagem', help_text='Informações')
    competence = models.ManyToManyField(Competence)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class GameSession(models.Model):
    game = models.ForeignKey('Game')                            # Game id
    user = models.ForeignKey('auth.User', related_name='game_session')                       # user id  que starded the session
    goal = models.IntegerField(verbose_name='Objetivo', null=True, blank=True)
    score = models.IntegerField(verbose_name='Resultado Final', null=True, blank=True) #Final result of the session
    finish = models.BooleanField(default=False) # 0 false 1 true
    level = models.ForeignKey('TypeLogSession')
    percent_finish = models.FloatField(verbose_name='Percentual', default=0, null=True, blank=True) #Final result of the session
    created_date = models.DateTimeField(auto_now_add=True)


class LogSession(models.Model):
    user = models.ForeignKey('auth.User', related_name='user_session') # user id  que starded the session
    game = models.ForeignKey('Game')                            # Game id
    session = models.ForeignKey('GameSession', related_name='log_session')
    type_log = models.ForeignKey('TypeLogSession')                            # Game id
    expected = models.IntegerField(verbose_name='Resultado esperado', null=True, blank=True)
    result = models.IntegerField(verbose_name='Resultado Alcançado', null=True, blank=True)
    score = models.IntegerField(verbose_name='Pontuação', null=True, blank=True)
    data = models.CharField(max_length=255, verbose_name='Dados', null=True, blank=True)
    competency = models.ForeignKey('Competence', null=True, blank=True)
    table_points = models.ForeignKey('TablePoints')
    created_date = models.DateTimeField(auto_now_add=True)


class TypeLogSession(models.Model):
    value = models.IntegerField(verbose_name='Valor')
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class CompetenceUser(models.Model):
    game = models.ForeignKey('Game')
    competency = models.ForeignKey('Competence', null=True, blank=True)
    user = models.ForeignKey('auth.User')
    level = models.ForeignKey('TypeLogSession')
    created_date = models.DateTimeField(auto_now_add=True)

# ######################################
# Models for resolve sessions user and
# ######################################e
class TablePoints(models.Model):
    game = models.ForeignKey('Game')
    competency = models.ForeignKey('Competence', null=True, blank=True)
    type_log = models.ForeignKey('TypeLogSession', null=True, blank=True)
    rule = models.CharField(max_length=255, verbose_name='Regra')
    score = models.IntegerField(verbose_name='Pontuacao', null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.rule + " " + self.type_log.name

templates/net/baysianet_detail.html
{% extends 'base.html' %}

{% block header %}
    <div class="page-header">
        <a href="" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="/">Rede Baysiana</a></h1>
    </div>
{% endblock %}

{% block content %}
    <div class="post">

        <h1>{{ baysianet.title }}</h1>
        <div class="date">
            <a class="btn btn-default" href="{% url 'competency_new' baysianet_pk=baysianet.pk%}"><span class="glyphicon glyphicon-plus"></span></a>
        </div>
        <h2>Hierarquias</h2>
        <div class="post">
            {% for key, value  in rede.items %}
                <h3>
                    {{ key.title}}
                    <a href="{% url 'ctp_new' key.pk baysianet.pk %} " data-toggle="tooltip" title="Add Tabela Condiconal"><span class="glyphicon glyphicon-plus"></span></a>
                    <a href="{% url 'ctp_detail' key.pk baysianet.pk %} " data-toggle="tooltip" title="Ver Tabela Condiconal"><span class="glyphicon glyphicon-eye-open"></span></a>

                </h3>
                    {% for hiera in value %}
                        {{ hiera.competency_child }}

                    {% endfor %}
                <hr/>
            {% endfor %}
        </div>
        <h2>Competências</h2>
        <div class="post">
            {% for competencia in baysianet.competency.all %}
                <h4>
                    <a href="{% url 'variable_new' competencia.pk baysianet.pk %} " data-toggle="tooltip" title="Add Variable"><span class="glyphicon glyphicon-plus"></span></a>
                    {{ competencia.title }} </h4>
                    {% for var in competencia.variable.all %}
                            {{ var.title }} {{ var.value }} |
                        {% endfor %}
                    {% for competency in competencia.competencs.all %}
                        <p>{{ competency.title }}</p>
                    {% endfor %}
            {% endfor %}
        </div>
    </div>
{% endblock %}


{% block list-group %}
    <ul class="list-group">
        <li class="list-group-item"><a href="{% url 'competency_new' baysianet.pk %}">Nova Competencia</a></li>
        <li class="list-group-item"><a href="{% url 'hierarchy_new' baysianet.pk %}">Nova Hierarquia</a></li>
        <li class="list-group-item">Morbi leo risus</li>
        <li class="list-group-item">Porta ac consectetur ac</li>
        <li class="list-group-item">Vestibulum at eros</li>
    </ul>
{% endblock %}

templates/net/competence_new.html
{% extends 'base.html' %}
{% block header %}
    <div class="page-header">
        <a href="" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="/">Rede Baysiana:</a> {{ baysianet.title }}</h1>
    </div>
{% endblock %}

{% block content %}
    <h1>Nova Competencia</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}

        {% if hierarchy_list %}
            <h2>Adicionar Hieraquia</h2>
            <select name="father" multiple="multiple">
            {% for h in hierarchy_list %}
                <option value="{{ h.pk }}">{{ h }}</option>
            {% endfor %}
            </select>
        {% endif %}

        <button type="submit" class="save btn btn-default">Guardar</button>
    </form>
{% endblock %}

templates/net/ctp_detail.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <div class="page-header">
        <a href="" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="/">Rede Baysiana: </a><span>{{ baysianet.title }}</span></h1>
    </div>
{% endblock %}

{% block content %}
    <h2> Conditional Probability Table</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        <table id="ctp-create-variables" class="table table-bordered">
            <thead>
                <tr class="head">
                {% for key, value  in ctp_dic_data.items %}
                <th class="tg-yw4l" colspan="5">P({{ key }} |  {% for key, value  in variable_dic_data.items %} {{ key }}, {% endfor %})</th>
            </tr>
                <tr  class="head">
                    {% for variables in value %}
                        <th>{{ key }}: {{ variables }} </th>
                    {% endfor %}
                    {% endfor %}
                    {% for key, value  in variable_dic_data.items %}
                        <th>{{ key }} </th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
            {% for i  in range %}
                <tr>
                    {% for key, value  in ctp_dic_data.items %}
                        {% for variables in value %}
                            <td class="father"><input id="{{ variables.pk }}" class="inputCTP" type="text"></td>

                        {% endfor %}
                    {% endfor %}
                    {% for key, value  in variable_dic_data.items %}
                        <td class="child">
                            <select id="id_variable_child" name="variable_child">
                                {{ key }}
                                {% for variable in value %}
                                    <option value="{{ variable.pk }}">{{ variable.value }}</option>
                                {% endfor %}
                            </select>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button id="save" type="button" class="save btn btn-default">Guardar</button>
        <span id="net">{{ baysianet }}</span>
        <span id="competency_father">{{ competency_father }}</span>
    </form>
{% endblock %}


{% block scripts %}
    <script type="text/javascript" src="{% static 'js/save_ctp.js' %}"></script>

{% endblock %}

templates/net/ctp_new.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <div class="page-header">
        <a href="" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="/">Rede Baysiana: </a><span>{{ baysianet.title }}</span></h1>
    </div>
{% endblock %}

{% block content %}
    <h2>Adicionar Conditional Probability Table</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        <table id="ctp-create-variables" class="table table-bordered">
            <thead>
                <tr class="head">
                {% for key, value  in ctp_dic_data.items %}
                <th class="tg-yw4l" colspan="5">P({{ key }} |  {% for key, value  in variable_dic_data.items %} {{ key }}, {% endfor %})</th>
            </tr>
                <tr  class="head">
                    {% for variables in value %}
                        <th>{{ key }}: {{ variables }} </th>
                    {% endfor %}
                    {% endfor %}
                    {% for key, value  in variable_dic_data.items %}
                        <th>{{ key }} </th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
            {% for i  in range %}
                <tr>
                    {% for key, value  in ctp_dic_data.items %}
                        {% for variables in value %}
                            <td class="father">{{ variables.pk }}<input id="{{ variables.pk }}" class="inputCTP" type="text"></td>

                        {% endfor %}
                    {% endfor %}
                    {% for key, value  in variable_dic_data.items %}
                        <td class="child">
                            <select id="id_variable_child" name="variable_child">
                                {{ key }}{{ key.pk }}
                                {% for variable in value %}
                                    <option value="{{ variable.pk }}">{{ variable.pk }} {{ variable.value }}</option>
                                {% endfor %}
                            </select>
                            <span class="line">{{ i }}</span>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <button id="save" type="button" class="save btn btn-default">Guardar</button>
        <span id="net">{{ baysianet.pk }}</span>
        <span id="competency_father">{{ competency_father }}</span>
    </form>
{% endblock %}


{% block scripts %}
    <script type="text/javascript" src="{% static 'js/save_ctp.js' %}"></script>

{% endblock %}

templates/net/hierarchy_new.html
{% extends 'base.html' %}
{% block header %}
    <div class="page-header">
        <a href="" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="/">Rede Baysiana:</a> {{ baysianet.title }}</h1>
    </div>
{% endblock %}

{% block content %}
    <h1>Nova Hierarquia</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}

        {% if hierarchy_list %}
            <h2>Adicionar Hierarquia</h2>
            <select name="father" multiple="multiple">
            {% for h in hierarchy_list %}
                <option value="{{ h.pk }}">{{ h }}</option>
            {% endfor %}
            </select>
        {% endif %}

        <button type="submit" class="save btn btn-default">Guardar</button>
    </form>
{% endblock %}

templates/net/variable_new.html
{% extends 'base.html' %}
{% block header %}
    <div class="page-header">
        <a href="" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="/">Rede Baysiana:</a> {{ context.baysianet.title }}</h1>
    </div>
{% endblock %}

{% block content %}
    <h2>Competência: {{ context.title }}</h2>
    <h3>Nova Variável</h3>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Guardar</button>
    </form>
{% endblock %}